In [1]:
import os
import numpy as np
import torchvision
from tqdm import tqdm
import pickle
np.random.seed(0)


In [2]:
dataset = "CIFAR10"
data_dir = os.path.join("./", dataset)
print('Data stored in %s' % data_dir)
if dataset == "CIFAR10":
    trainset = torchvision.datasets.CIFAR10(root=data_dir, train=True, download=True, transform=None)
else:
    trainset = torchvision.datasets.CIFAR100(root=data_dir, train=True, download=True, transform=None)
vic_num = len(trainset) // 2
vic_idx = np.random.choice(len(trainset), vic_num, replace=False)
print(vic_idx) 

Data stored in ./data/CIFAR10
Files already downloaded and verified
[11841 19602 45519 ... 18418 29236 37107]


In [3]:
X_list = []
y_list = []
# recover from np.array
# from PIL import Image
# im = Image.fromarray(X_train_list[0])
for data in tqdm(trainset):
    x, y = data
    X_list.append(np.array(x))
    y_list.append(y)

100%|██████████| 50000/50000 [00:01<00:00, 32225.17it/s]


In [4]:
X_np = np.array(X_list)
y_np = np.array(y_list)

In [5]:
X_set1 = X_np[vic_idx]
y_set1 = y_np[vic_idx]
X_set2 = X_np[~vic_idx]
y_set2 = y_np[~vic_idx]

In [6]:
pickle.dump(((X_set1, y_set1), (X_set2, y_set2)), open("./{}_sub_train_split.pkl".format(dataset), "wb"))

# compute mean and std

In [7]:
import torchvision.transforms as transforms
import torch

In [8]:
totensor = transforms.ToTensor()

In [9]:
X_all_list = []
for data in tqdm(trainset):
    x, _ = data
    X_all_list.append(totensor(x))

100%|██████████| 50000/50000 [00:03<00:00, 16397.24it/s]


In [10]:
X_tensor = torch.stack(X_all_list)

# all 

In [11]:
X_tensor.mean(dim=[0,2,3]).numpy()

array([0.4914008 , 0.482159  , 0.44653094], dtype=float32)

In [12]:
X_tensor.std(dim=[0,2,3]).numpy()

array([0.24703224, 0.24348514, 0.26158786], dtype=float32)

## subset1

In [13]:
X_tensor[torch.tensor(vic_idx)].mean(dim=[0,2,3]).numpy()

array([0.49115923, 0.4816946 , 0.4456668 ], dtype=float32)

In [14]:
X_tensor[torch.tensor(vic_idx)].std(dim=[0,2,3]).numpy()

array([0.24728498, 0.24360786, 0.26152962], dtype=float32)

## subset2

In [15]:
X_tensor[~torch.tensor(vic_idx)].mean(dim=[0,2,3]).numpy()

array([0.49106905, 0.4816098 , 0.4461698 ], dtype=float32)

In [16]:
X_tensor[~torch.tensor(vic_idx)].std(dim=[0,2,3]).numpy()

array([0.24676642, 0.24312036, 0.26133248], dtype=float32)